// The Young-D-Guide association library: lyric concepts → meaning → emotion → motif world →
// shot ideas in six directions and three weirdness levels. Every idea carries its "why":
// the associative bridge that keeps weird from becoming random.
//
// Idea tuple: [direction, level, idea, why, doThis (" / " separated), spec, tags, motifs, ai?]
//   direction: literal | object | metaphor | weird | practical | hybrid
//   level:     0 safe · 1 strange · 2 unhinged
//   spec:      "size|camera position|movement|lens|fps|lighting|location|prop;prop"
//   tags:      cheap solo street luxury cinematic emotional minimal surreal ai crew
//   motifs:    from MOTIFS below — used to keep a video's visual world cohesive
//   ai:        what compositing / AI generation the idea needs, if any
// All ideas are original to ReaShoota.

export const MOTIFS = ['water', 'glass', 'mirrors', 'ice', 'plastic', 'cctv', 'cars', 'flowers', 'chrome', 'televisions', 'elevators', 'food', 'chairs', 'light', 'smoke'];

export const CONCEPTS = [
  {
    id: 'watched', label: 'Being watched',
    match: /\b(watch\w*|stare|staring|stares|eyes on|all eyes|looking at me|look at me|see me|seen|spy\w*|followed|following me|cameras?|audience)\b/i,
    meaning: 'Scrutiny — every move is observed and judged.', emotion: 'exposed, paranoid, famous',
    motifs: ['cctv', 'televisions', 'glass', 'mirrors'],
    ideas: [
      ['literal', 0, 'A quiet street where every stranger turns their head in sync as the artist walks past.', 'Makes the feeling of being watched physical and synchronised.', 'Walk at an even pace / Extras turn heads on your cue beat / Don’t react', 'WS|eye level|slow tracking|0.5x|24|overcast daylight|quiet street|', 'crew,cinematic', 'glass'],
      ['object', 0, 'Every rear-view and side mirror on a row of parked cars is angled toward the artist.', 'Mirrors are how we check who’s behind us — here they all check him.', 'Angle the mirrors first / Stand in the middle of the row / Look straight ahead', 'MS|low angle|static|2x|24|golden hour|parked street|car mirrors', 'street,solo', 'mirrors,cars'],
      ['metaphor', 1, 'A crowd stands facing away while dozens of phones on sticks point back at one person.', 'Attention without connection: everyone films, no one looks.', 'Crowd faces the wall / Phones held over shoulders toward you / You sing into the lenses', 'WS|high angle|slow push-in|0.5x|24|flat white light|car park or hall|phones;selfie sticks', 'crew,cinematic', 'televisions,cctv'],
      ['weird', 1, 'Perform in front of a wall of old TVs, each showing you half a second late.', 'The delay makes the observers feel like they’re chasing and copying you.', 'Stack TVs or monitors / Loop your live feed with a delay / Perform facing camera', 'MS|eye level|static|1x|24|TV glow only|dark room|old TVs;HDMI splitter', 'cinematic', 'televisions,cctv'],
      ['weird', 2, 'The artist eats dinner alone while security cameras slowly sprout from the walls like plants, all turning to follow his fork.', 'Surveillance growing on its own — paranoia as a living thing.', 'Eat calmly / Never look at the cameras / Slow bites on the beat', 'MS|eye level|locked-off|1x|24|single practical lamp|dining room|table;plate;dummy cameras', 'surreal,cinematic', 'cctv,food', 'Animate cameras growing from the wall (AI video or stop-motion)'],
      ['practical', 0, 'Shoot through three friends’ phone screens held up at the artist, the real artist blurred behind.', 'You see him the way everyone sees him: through a screen.', 'Friends hold phones in record mode / Focus on the screens / Rack to you on the lyric', 'MCU|chest height|handheld|2x|30|natural light|anywhere|3 phones', 'cheap,street', 'televisions'],
      ['hybrid', 2, 'Real performance plus generated camera lenses orbiting the artist like moons.', 'Being watched becomes a solar system with the artist at the centre.', 'Perform locked-off / Leave space around your head / Keep still between lines', 'MCU|eye level|static|1x|24|hard key, dark background|studio or bedroom|', 'ai,surreal', 'cctv,glass', 'Generate orbiting lenses and composite over the plate'],
      ['weird', 1, 'In a fitting-room mirror, the reflection keeps checking on the artist even after he looks away.', 'The watcher is yourself — self-surveillance.', 'Look into the mirror / Turn away on the beat / Reflection shot is a second take', 'MS|over the shoulder|static|1x|24|fitting-room downlight|changing room|mirror', 'solo,surreal', 'mirrors', 'Split-screen two takes in the mirror'],
    ],
  },
  {
    id: 'cold', label: 'Cold heart',
    match: /\b(cold|colder|ice|icy|iced|froze|freeze|frozen|numb|winter|chill\w*|frost\w*)\b/i,
    meaning: 'Emotional shutdown — feeling nothing on purpose.', emotion: 'numb, controlled, detached',
    motifs: ['ice', 'glass', 'chrome', 'food'],
    ideas: [
      ['literal', 0, 'Breath visible in a dark room lit by one hard light from above.', 'Cold you can see — and it’s coming out of him.', 'Stand under the light / Exhale slowly on the lyric / Hold eye contact', 'CU|eye level|static|2x|60|hard top light|cold room or night outside|', 'minimal,solo', 'light,smoke'],
      ['object', 0, 'A single rose sealed in a block of ice, melting under a desk lamp.', 'Love preserved by freezing it — beauty you can’t touch.', 'Freeze a rose in a tub overnight / Place under a lamp / Shoot the drips', 'ECU|overhead|slow push-in|2x|60|warm desk lamp|kitchen table|ice block;rose;lamp', 'cheap,emotional', 'ice,flowers'],
      ['metaphor', 1, 'A formal dinner table set inside a walk-in freezer; the artist dines alone in a suit.', 'Elegance with no warmth — a life that looks good but feels cold.', 'Sit upright / Eat slowly / Frost on the cutlery', 'WS|eye level|static|0.5x|24|cold white fluorescent|walk-in freezer or cold store|table;cutlery;candles', 'luxury,cinematic', 'ice,food'],
      ['weird', 2, 'The artist eats dinner calmly while everything on the table freezes over except him and his plate.', 'He is the coldest thing in the room — the cold spreads from him.', 'Eat without reacting / Keep hands on the table / Lock the frame', 'MS|eye level|locked-off|1x|24|silver moonlight key|dining room|table;plates;glasses', 'surreal,cinematic', 'ice,food', 'Animate frost spreading across the table (AI video or VFX)'],
      ['practical', 0, 'A fogged bathroom mirror, silver lighting; wipe one line through the steam to reveal the face on the lyric.', 'The reveal is cold and clean — a face behind condensation.', 'Run a hot shower first / Light with a cool LED / Wipe on the downbeat', 'CU|eye level|static|1x|30|cool LED|bathroom|mirror', 'cheap,solo,minimal', 'mirrors,glass'],
      ['weird', 1, 'The artist hands someone a steaming cup of tea; it comes back frozen solid.', 'Warmth offered to him turns cold on contact.', 'Hand the cup across / Cut on the beat / Return a frozen cup (freeze one first)', 'MS|eye level|static|1x|24|warm kitchen light|kitchen|two identical mugs', 'solo,cheap', 'ice,food'],
      ['hybrid', 1, 'Frost crawls across the lens as the line lands.', 'The camera itself goes cold — the audience feels it too.', 'Shoot through a glass pane / Spray frost spray on the beat / Stay in focus behind', 'MCU|through glass|static|1x|30|backlight|anywhere|glass pane;frost spray', 'cheap,cinematic', 'ice,glass', 'Optional: AI frost growth over the final frames'],
    ],
  },
  {
    id: 'switched', label: 'Switching sides',
    match: /\b(switch\w*|switched sides|turned on me|turn(ed)? my back|betray\w*|snakes?|two[- ]faced|fake friends?|backstab\w*|traitors?|flipp?ed|swapped)\b/i,
    meaning: 'Loyalty reversing — people you trusted now on the other team.', emotion: 'betrayed, cold, clear-eyed',
    motifs: ['chairs', 'elevators', 'mirrors'],
    ideas: [
      ['literal', 0, 'Friends walking beside the artist peel off one by one and cross to the other side of the street.', 'Switching sides shown as geography.', 'Walk forward steadily / Each friend crosses on a beat / End alone on one side', 'WS|eye level|backwards tracking|0.5x|24|daylight|wide street|', 'crew,street', 'cars'],
      ['object', 0, 'Chess pieces change colour between cuts while the artist keeps playing.', 'The same pieces, now working for the opponent.', 'Set up two chess sets / Swap one piece per cut / Artist moves on the beat', 'CU|overhead|static|1x|24|single lamp|table|chess sets', 'cheap,solo,minimal', 'chairs'],
      ['metaphor', 1, 'The artist enters an elevator full of friends; the doors close, and when they open everyone faces the wall.', 'The ride was short and everything changed — no one says why.', 'Friends face you as doors close / Cut / Reopen with everyone turned away', 'MS|eye level|static|1x|24|elevator light|elevator|', 'crew,cinematic', 'elevators'],
      ['weird', 2, 'A football match where both teams swap shirts mid-play and carry on as though nothing happened.', 'Sides switching as if it’s normal — which is the betrayal.', 'Two groups in bibs / Swap on the beat / Keep playing', 'WS|high angle|static|0.5x|30|floodlights|five-a-side pitch|bibs;ball', 'crew,street,surreal', 'light'],
      ['practical', 0, 'Two mirrors angled so the same friend appears on opposite sides of frame.', 'One person, two sides.', 'Place mirrors in a V / Friend stands in the gap / Artist in the middle', 'MS|eye level|static|1x|24|soft window light|bedroom|2 mirrors', 'cheap,solo', 'mirrors'],
      ['weird', 1, 'A group photo retaken on every beat; each time one more person is facing the other way.', 'The loyalty count dropping, frame by frame.', 'Lock the phone on a tripod / Everyone holds still / One person turns per shot', 'WS|eye level|locked-off|0.5x|stills|flash|anywhere|tripod', 'crew,cheap', 'light'],
      ['hybrid', 2, 'In one street shot, everyone’s clothes flip colour in a wave that starts behind the artist.', 'The switch spreads through the crowd like a rumour.', 'Artist walks toward camera / Crowd crosses naturally / Hold the wide', 'WS|eye level|slow push-in|0.5x|24|daylight|busy street|', 'ai,crew', 'plastic', 'AI video colour-swap wave across the crowd'],
    ],
  },
  {
    id: 'carry', label: 'Carrying the weight',
    match: /\b(carry\w*|carried|whole team|on my back|shoulders?|weight|hold it down|burden|lift\w*|heavy)\b/i,
    meaning: 'Responsibility — everyone depends on one person.', emotion: 'strong, tired, proud',
    motifs: ['chairs', 'cars', 'food'],
    ideas: [
      ['literal', 0, 'The artist carries a big speaker on his shoulder through the city, still playing the song.', 'He literally carries the sound everyone is moving to.', 'Shoulder the speaker / Walk toward camera / Song plays from it', 'MS|low angle|backwards tracking|1x|24|daylight|city street|speaker', 'street,solo', 'cars'],
      ['metaphor', 0, 'The artist pushes a car with the whole crew sitting inside it, relaxed.', 'Everyone rides; one person pushes.', 'Crew sits calmly / Push from the back / Slow, heavy steps', 'WS|low angle|static|0.5x|24|golden hour|empty road|car', 'crew,street', 'cars'],
      ['object', 0, 'One chair holding up a tower of ten chairs balanced on it.', 'The foundation nobody notices.', 'Stack chairs safely / Artist sits on the bottom one / Hold still', 'WS|eye level|static|1x|24|single top light|hall|chairs', 'minimal,cinematic', 'chairs'],
      ['weird', 1, 'Boardroom table where every other chair is tied by rope to the artist’s chair; when he stands, they all slide toward him.', 'Everyone attached to one person’s movement.', 'Tie ropes under the table / Stand on the lyric / Crew slides with a pull', 'WS|high angle|static|0.5x|24|cold office light|meeting room|table;chairs;rope', 'crew,surreal,cinematic', 'chairs'],
      ['weird', 2, 'The artist walks down the street with a miniature football stadium strapped to his back while the game keeps playing.', 'Carrying the team — literally the whole match on his back.', 'Wear a backpack rig / Walk steadily / Don’t acknowledge it', 'MS|eye level|tracking|1x|24|daylight|high street|backpack', 'surreal,ai', 'light', 'Composite a tiny live stadium onto the backpack'],
      ['practical', 0, 'Low angle: the artist lifts a crate holding one shoe from each crew member and walks off.', 'Each shoe is a person he carries.', 'Collect a shoe from everyone / Lift on the beat / Walk out of frame', 'MS|low angle|static|0.5x|30|hallway light|corridor|crate;shoes', 'cheap,solo', 'plastic'],
      ['hybrid', 1, 'The crew shrunk to tiny figures riding on the artist’s shoulders, pointing the way.', 'He’s the vehicle for everyone’s journey.', 'Shoot the artist walking / Shoot crew separately on green or plain wall / Match light', 'MS|eye level|tracking|1x|24|soft daylight|street|', 'ai,crew', 'light', 'Composite scaled-down crew onto the shoulders'],
    ],
  },
  {
    id: 'money', label: 'Money & status',
    match: /\b(money|cash|rich|paid|bands|racks|bread|dollars?|rands?|bank|wealth|pockets?|million\w*|bills|price|expensive|drip)\b/i,
    meaning: 'Value, status and what it costs you.', emotion: 'hungry, proud, uneasy',
    motifs: ['chrome', 'plastic', 'food'],
    ideas: [
      ['literal', 0, 'Receipt printer spitting an endless receipt across a marble floor.', 'Wealth measured in what it costs.', 'Feed a long receipt roll / Let it pile / Artist steps over it', 'MS|low angle|slow push-in|1x|60|clean white light|shop or lobby|receipt roll', 'luxury,minimal', 'plastic'],
      ['object', 1, 'Price tags hang from everything in the room — the lamp, the sofa, the artist’s ear.', 'When everything has a price, so do you.', 'Tag every object / Tag your ear last / Deliver the line to camera', 'MCU|eye level|static|2x|24|warm lamps|living room|price tags', 'cheap,solo', 'plastic'],
      ['metaphor', 1, 'The artist sits in a laundromat watching one machine spin full of shredded notes.', 'Money laundered into confetti — worthless and still spinning.', 'Fill a machine with shredded paper / Sit opposite / Watch it, not the camera', 'MS|eye level|static|1x|24|fluorescent tubes|laundromat|shredded paper', 'street,cinematic', 'glass,chrome'],
      ['weird', 2, 'At the barber, the barber sweeps up coins instead of hair.', 'Every cut, value falls off him — he sheds money like it’s nothing.', 'Scatter coins on the floor / Sweep on the beat / Artist admires the fade', 'MS|high angle|static|1x|30|barber shop light|barber shop|coins;broom', 'street,surreal', 'chrome'],
      ['weird', 1, 'A fridge filled entirely with gift boxes; the artist picks one like a midnight snack.', 'Luxury as a habit, not an event.', 'Stack gift boxes in a fridge / Open on the beat / Fridge light only', 'MS|inside the fridge|static|0.5x|24|fridge light|kitchen|gift boxes', 'luxury,solo', 'food'],
      ['practical', 0, 'Night: the artist lit only by an ATM screen, slow push-in as the line lands.', 'Money as the only light source in his life.', 'Stand at an ATM at night / Screen lights your face / Slow push toward you', 'CU|eye level|slow push-in|2x|24|ATM screen glow|street ATM|', 'cheap,solo,street', 'light'],
      ['hybrid', 2, 'It rains receipts instead of water; puddles reflect gold.', 'The weather of a money-obsessed world.', 'Perform on a wet street / Look up on the lyric / Keep an open umbrella', 'WS|low angle|static|0.5x|24|streetlights|wet street|umbrella', 'ai,luxury', 'water,light', 'Generate falling receipts and gold reflections'],
    ],
  },
  {
    id: 'speed', label: 'Speed & cars',
    match: /\b(fast|speed\w*|driv\w*|drove|car|cars|whip|ride|riding|racing|race|highway|gas|pedal|engine|traffic|taxi|lanes?)\b/i,
    meaning: 'Momentum, status and escape — never slowing down.', emotion: 'restless, cool, reckless',
    motifs: ['cars', 'light', 'chrome', 'ice'],
    ideas: [
      ['literal', 0, 'Headlights sweep across the artist’s face from the passenger seat at night.', 'Speed felt as light passing, not as scenery.', 'Sit in a parked car / A friend sweeps a torch across / Stay still', 'CU|eye level|static|2x|24|moving torch as headlights|parked car|torch', 'cheap,solo', 'light,cars'],
      ['object', 1, 'A convertible filled to the brim with ice, parked under one streetlight.', 'Cool as an object — a car that can’t be driven, only admired.', 'Fill the seats with ice bags / Artist sits on the bonnet / Hold the wide', 'WS|eye level|static|0.5x|24|single streetlight|empty lot|car;ice', 'luxury,surreal', 'ice,cars'],
      ['metaphor', 1, 'A car slowly rotates on a turntable in an empty supermarket aisle.', 'Status on display in the most ordinary place — speed with nowhere to go.', 'Place the car or a toy car on a turntable / Artist walks the aisle / Slow rotation', 'WS|eye level|slow dolly|0.5x|24|supermarket fluorescents|empty shop|turntable', 'surreal,cinematic', 'cars,plastic'],
      ['weird', 2, 'Headlights reveal a full dinner table set in the middle of the road; the car stops and the artist gets out and sits down.', 'The journey interrupted by an appointment he can’t skip.', 'Park headlights on the table / Walk into frame / Sit on the downbeat', 'WS|low angle|static|0.5x|24|car headlights only|quiet road|table;chairs;car', 'cinematic,surreal', 'cars,food,light'],
      ['weird', 1, 'The car seen through aquarium glass, as if it’s swimming.', 'Speed slowed into something dreamy and trapped.', 'Put a fish tank in front of the lens / Car passes behind / Rack focus', 'MS|through glass|static|1x|60|daylight|street with a tank on a table|fish tank or water tank', 'cheap,surreal', 'water,glass,cars'],
      ['practical', 0, 'Phone on a skateboard at bumper height, rolling past the artist standing still.', 'Makes stillness feel fast.', 'Tape phone to a skateboard / Friend pushes it past / Stand dead still', 'MS|ground level|dolly past|0.5x|60|daylight|pavement|skateboard', 'cheap,street', 'cars'],
      ['hybrid', 1, 'Streetlights stretch into light trails behind a completely static artist.', 'The world rushing while he stays in control.', 'Stand still at night / Traffic behind you / Hold the frame', 'MCU|eye level|locked-off|1x|24|streetlights|roadside|', 'ai,cinematic', 'light,cars', 'Long-exposure trails via AI or frame blending'],
    ],
  },
  {
    id: 'love', label: 'Love',
    match: /\b(love\w*|lover|baby|babe|kiss\w*|hold you|together|mine|romance|miss you|darling|my girl|my man|forever you)\b/i,
    meaning: 'Closeness — two people choosing each other.', emotion: 'tender, longing, safe',
    motifs: ['flowers', 'light', 'water', 'glass'],
    ideas: [
      ['literal', 0, 'Two hands almost touching across a café table, shallow focus.', 'The gap before contact is where longing lives.', 'Slide hands closer on each beat / Never quite touch until the lyric', 'ECU|eye level|static|3x|60|window light|café|table', 'emotional,minimal', 'food,light'],
      ['object', 0, 'Two glasses of water poured into one.', 'Two becoming one, in the simplest possible object.', 'Pour both at once / Shoot against a dark background / Slow motion', 'CU|eye level|static|2x|120|backlight|kitchen|3 glasses;water', 'cheap,minimal', 'water,glass'],
      ['metaphor', 1, 'Two people share one pair of earphones through a glass wall that separates them.', 'Connected by the song, separated by everything else.', 'Thread the cable through a gap / Each on one side / Sing to each other', 'MS|profile|static|1x|24|soft daylight|shop window|earphones', 'emotional,cinematic', 'glass'],
      ['weird', 1, 'A houseplant that leans toward the artist wherever he moves in the room.', 'Love as something that grows toward you.', 'Move the plant between cuts / You walk around the room / Keep plant in frame', 'WS|eye level|static|0.5x|24|window light|living room|plant', 'solo,surreal,cheap', 'flowers'],
      ['weird', 2, 'In a flower shop, the florist wires roses to a heart-rate monitor beeping in time with the song.', 'A heartbeat you can see, grown into flowers.', 'Place a monitor prop among flowers / Florist works calmly / Beeps match the beat', 'MS|eye level|slow push-in|1x|24|warm shop light|florist|monitor prop;roses', 'surreal,crew', 'flowers,televisions'],
      ['practical', 0, 'The artist’s reflection in a lover’s sunglasses as they sing the line.', 'You see him through their eyes — literally.', 'Partner wears mirrored shades / Frame the lenses / Artist performs behind camera', 'ECU|eye level|static|3x|24|daylight|outdoors|mirrored sunglasses', 'cheap', 'mirrors,glass'],
      ['hybrid', 2, 'Flowers bloom across a concrete wall in the beat pattern as the artist sings.', 'Love making something grow where nothing should.', 'Perform against a plain wall / Leave space / Hold still between lines', 'MS|eye level|static|1x|24|soft side light|concrete wall|', 'ai,emotional', 'flowers', 'Generate blooming flowers synced to beats'],
    ],
  },
  {
    id: 'pain', label: 'Heartbreak & pain',
    match: /\b(hurt\w*|pain\w*|broke|broken|heartbreak\w*|tears?|cry\w*|cried|scars?|bleed\w*|wound\w*|ache)\b/i,
    meaning: 'Damage that doesn’t heal on schedule.', emotion: 'raw, fragile, stubborn',
    motifs: ['glass', 'water', 'food'],
    ideas: [
      ['literal', 0, 'A single tear, extreme close-up, backlit so it glows.', 'The smallest honest image of hurt.', 'Backlight your face / Use a glycerin drop if needed / Blink on the beat', 'ECU|eye level|static|3x|60|hard backlight|dark room|', 'emotional,minimal,solo', 'water,light'],
      ['object', 0, 'A drinking glass cracks slowly under a bass hit.', 'Pressure you can see, landing on the beat.', 'Score a glass safely or use a sugar-glass prop / Tap on the beat / Slow motion', 'ECU|eye level|static|2x|240|backlight|table|glass', 'cheap,cinematic', 'glass'],
      ['metaphor', 1, 'The artist glues a smashed plate back together while it keeps cracking in new places.', 'Trying to fix what keeps breaking.', 'Pre-break a plate / Glue pieces on camera / Crack a new line each beat', 'CU|overhead|static|1x|24|warm lamp|kitchen table|plate;glue', 'emotional,solo', 'food'],
      ['weird', 2, 'In a dentist’s chair, a nurse tries to extract a small heart-shaped stone from the artist’s mouth.', 'Removing the thing that hurts — clinically, painfully.', 'Lie back / Keep singing the line / Nurse holds up the stone at the end', 'MCU|overhead|static|1x|24|clinical white light|dentist or white room|stone prop', 'surreal,crew', 'glass', ''],
      ['weird', 1, 'Rain falls indoors, only on the artist’s side of the sofa.', 'Grief as personal weather.', 'Friend pours water from above one side / You sit still / Other side stays dry', 'WS|eye level|static|0.5x|60|window light|living room|watering can;plastic sheet', 'cheap,surreal', 'water'],
      ['practical', 0, 'Shoot through shower glass with water streaming between camera and artist.', 'Blurred, overwhelmed, trying to speak through it.', 'Run the shower on the glass / Stand behind it / Sing through', 'MCU|through glass|static|1x|30|bathroom light|bathroom|', 'cheap,solo', 'water,glass'],
      ['hybrid', 1, 'Cracks spread across the artist’s skin like porcelain, then heal on the next line.', 'Breaking and holding together at the same time.', 'Clean close-up / Keep still / Even light', 'CU|eye level|static|2x|24|soft even light|anywhere|', 'ai,emotional', 'glass', 'Porcelain crack effect on skin (AI video)'],
    ],
  },
  {
    id: 'alone', label: 'Alone',
    match: /\b(alone|lonely|lonesome|by myself|nobody|no one|empty|solo|on my own|isolat\w*)\b/i,
    meaning: 'Isolation — the room is full of space.', emotion: 'quiet, heavy, self-reliant',
    motifs: ['chairs', 'elevators', 'food', 'light'],
    ideas: [
      ['literal', 0, 'One person at a bus stop in a huge, empty wide frame.', 'Scale makes loneliness readable.', 'Tiny in frame / No movement / Hold for the whole line', 'EWS|eye level|locked-off|0.5x|24|dusk light|bus stop|', 'solo,minimal', 'light'],
      ['object', 0, 'A birthday cake with one candle at a twelve-seat table.', 'A celebration planned for many, attended by one.', 'Set the long table / Light one candle / Blow it out on the beat', 'WS|eye level|static|0.5x|24|candle light|dining room|cake;chairs', 'emotional,cinematic', 'food,chairs'],
      ['metaphor', 1, 'A full stand of seats, each holding an empty jacket; the artist performs to them.', 'An audience that looks full but isn’t there.', 'Lay jackets on seats / Perform to them / Wide then close', 'WS|low angle|slow push-in|0.5x|24|stadium or hall light|stands|jackets', 'cinematic,surreal', 'chairs'],
      ['weird', 2, 'The artist plays a two-player board game against himself, switching seats every beat, each version slightly more tired.', 'When you’re alone long enough you become your own company.', 'Two outfits / Switch seats per cut / Get more tired each time', 'MS|eye level|locked-off|1x|24|single lamp|table|board game;2 chairs', 'solo,surreal', 'chairs', 'Split-screen two takes'],
      ['weird', 1, 'An elevator stops at every floor; the doors open onto identical empty corridors.', 'Going somewhere, arriving nowhere.', 'Ride an elevator / Film each door opening / Stay in the corner', 'MS|eye level|static|0.5x|24|elevator light|elevator|', 'solo,cinematic', 'elevators'],
      ['practical', 0, 'Locked-off wide of an empty laundromat at night, artist in the last chair.', 'Everyday loneliness under fluorescent light.', 'Sit in the far chair / Machines spinning / Sing quietly', 'WS|eye level|locked-off|0.5x|24|fluorescent tubes|laundromat|', 'cheap,solo,street', 'light,chairs'],
      ['hybrid', 2, 'A busy city at noon with every person digitally removed except the artist.', 'The crowd erased — how it feels inside.', 'Walk through a busy street / Locked or smooth move / Keep your pace even', 'WS|eye level|tracking|0.5x|24|daylight|busy street|', 'ai,cinematic', 'glass', 'AI remove all other people from the shot'],
    ],
  },
  {
    id: 'rise', label: 'Rising up',
    match: /\b(rise|rising|rose|up now|top|made it|winning|win|won|climb\w*|level up|came up|higher|elevat\w*|success|on top)\b/i,
    meaning: 'Upward momentum — leaving the ground floor behind.', emotion: 'triumphant, hungry, relieved',
    motifs: ['elevators', 'light', 'chrome', 'chairs'],
    ideas: [
      ['literal', 0, 'Spiralling up a stairwell with the artist, one flight per beat.', 'Progress you can count.', 'Climb steadily / Camera follows below / Cut on each landing', 'MS|low angle|spiral follow|0.5x|30|stairwell light|stairwell|', 'solo,street', 'light'],
      ['object', 1, 'Elevator floor numbers keep climbing past the building’s top floor.', 'Going higher than the building allows.', 'Film the floor display / Add numbers in edit / Artist watches calmly', 'CU|eye level|static|2x|24|elevator light|elevator|', 'cheap,surreal', 'elevators'],
      ['metaphor', 1, 'The artist stands on a bathroom scale that shows a bigger number every time he sings.', 'Weight as worth — he’s growing.', 'Stand on a digital scale / Cut to the display per line / Look pleased', 'CU|high angle|static|1x|24|bathroom light|bathroom|scale', 'cheap,solo', 'plastic'],
      ['weird', 2, 'The artist climbs a mountain made of stacked school desks and other people’s trophies.', 'Rising by climbing over every system that doubted him.', 'Stack desks safely / Climb slowly / Summit on the chorus', 'WS|low angle|slow tilt up|0.5x|24|golden hour|yard or field|desks;trophies', 'surreal,crew', 'chairs,chrome', 'Optional AI extension of the pile'],
      ['weird', 1, 'Every step the artist takes lights up the next floor tile like a scoreboard.', 'Every move counted, every step a point.', 'Walk forward on the beat / Tile light added in edit or with LED strip', 'WS|high angle|static|0.5x|24|dark room|hall|LED strips', 'cinematic', 'light'],
      ['practical', 0, 'Start at ground level and cut to one flight higher on each beat until you’re on the roof.', 'Rising told in a stack of jump cuts.', 'Same framing each floor / Cut on beats / End on the skyline', 'MS|eye level|static|1x|24|daylight|building stairs|', 'cheap,solo', 'elevators'],
      ['hybrid', 2, 'The artist rises out of a sea of clouds that are really macro shots of smoke in a glass.', 'Heaven built on a tabletop — scale as ambition.', 'Shoot smoke in a glass macro / Shoot artist against sky / Composite', 'MS|low angle|slow push-in|1x|60|backlight|rooftop|glass;incense', 'ai,cinematic', 'smoke,glass', 'Composite artist into macro smoke clouds'],
    ],
  },
  {
    id: 'fall', label: 'Falling',
    match: /\b(fall\w*|fell|down|drop\w*|lost|losing|sink\w*|sank|crash\w*|slipp\w*)\b/i,
    meaning: 'Losing control — the floor giving way.', emotion: 'dizzy, defeated, surrendering',
    motifs: ['water', 'chairs', 'elevators'],
    ideas: [
      ['literal', 0, 'The artist falls backward onto a bed in slow motion, arms open.', 'Surrender, shot gently.', 'Fall back safely / Shoot at 120fps / Land on the beat', 'MS|high angle|static|0.5x|120|window light|bedroom|bed', 'cheap,solo,emotional', 'light'],
      ['object', 0, 'A chair tipping over in slow motion, landing exactly on the beat.', 'The seat of control giving way.', 'Tip a chair with fishing line / Shoot slow motion / Hit the beat', 'WS|ground level|static|0.5x|240|hard side light|empty room|chair', 'cheap,minimal', 'chairs'],
      ['metaphor', 1, 'The artist rides an escalator down while everyone else rides up.', 'Going against the flow — down while the world climbs.', 'Ride the down escalator / Crowd goes up / Face camera', 'MS|eye level|static|1x|24|mall light|mall|', 'street,cinematic', 'elevators'],
      ['weird', 2, 'The artist slowly sinks into the sofa like quicksand while the family keeps watching TV.', 'Drowning in plain sight at home.', 'Sit in cushions / Sink between cuts / Family doesn’t react', 'WS|eye level|locked-off|0.5x|24|TV glow|living room|sofa', 'surreal,crew', 'televisions,chairs', 'Optional AI sinking effect'],
      ['weird', 1, 'Balloons tied to the artist’s wrist drift downward instead of up.', 'Even hope is falling.', 'Weigh balloons with water / Hold the string / Let them drop on the beat', 'MS|eye level|static|1x|60|daylight|street|balloons', 'cheap,surreal', 'plastic'],
      ['practical', 0, 'POV: the artist’s hand drops the phone; it tumbles onto a soft mat, still recording.', 'The camera falls with him.', 'Hold phone at arm’s length / Drop onto cushions / Keep rolling', 'POV|hand height|drop|0.5x|60|daylight|anywhere|cushions', 'cheap,solo', 'televisions'],
      ['hybrid', 2, 'The artist falls through the floors of rooms from his life, each a different year.', 'Falling through your own history.', 'Shoot falls onto a mat against plain wall / Shoot rooms separately / Composite', 'WS|overhead|static|0.5x|60|varied|studio|mat', 'ai,cinematic', 'chairs', 'Composite fall through stacked rooms'],
    ],
  },
  {
    id: 'night', label: 'Night & city',
    match: /\b(night\w*|midnight|late|city|streets?|[1-4] ?am|streetlights?|dark|downtown|moon)\b/i,
    meaning: 'The city after hours — freedom and danger in the same light.', emotion: 'awake, restless, cinematic',
    motifs: ['light', 'cars', 'glass', 'televisions'],
    ideas: [
      ['literal', 0, 'The artist under a single flickering streetlight on an empty corner.', 'Night reduced to one pool of light.', 'Stand in the light pool / Hold still / Flicker on the beat', 'WS|eye level|static|0.5x|24|streetlight|corner|', 'cheap,solo,street', 'light'],
      ['object', 0, 'A vending machine glowing in the dark is the only thing lit on the block.', 'The city’s last open door.', 'Find a lit machine / Artist leans on it / Buy something on the beat', 'MS|eye level|static|1x|24|machine glow|street|', 'street,cheap', 'light,plastic'],
      ['metaphor', 1, 'A shop window full of switched-on TVs, all showing the same dark street the artist stands in.', 'The city watching itself at night.', 'Find a TV shop or stack screens / Artist outside / Reflections overlap', 'MS|through glass|static|1x|24|screen glow|shopfront|', 'cinematic', 'televisions,glass'],
      ['weird', 2, 'At 3 a.m. the artist does his laundry at an outdoor laundromat in the middle of a roundabout.', 'Private routines exposed in the loudest public place.', 'Set machines or baskets on a traffic island / Fold calmly / Cars circle', 'WS|high angle|static|0.5x|24|streetlights|traffic island|laundry basket', 'surreal,street', 'cars,light'],
      ['weird', 1, 'Every window in a block of flats lights up in sequence with the melody.', 'The city playing along.', 'Wide on a block / Artist on the street / Light cues in edit', 'EWS|low angle|static|0.5x|24|night|housing block|', 'cinematic,ai', 'light', 'Animate window lights to the melody'],
      ['practical', 0, 'Artist filmed through a rain-streaked bus window, city lights smeared behind.', 'Night as texture.', 'Sit by a bus window / Film from outside or reflection / Night drive', 'MCU|through glass|handheld|2x|24|city lights|bus|', 'cheap,solo,street', 'glass,water'],
      ['hybrid', 2, 'The moon rolls down the street like a streetlight that came loose.', 'Night itself loose in the city.', 'Shoot the empty street / Artist watches it pass / Hold the wide', 'WS|low angle|static|0.5x|24|streetlights|long street|', 'ai,surreal', 'light', 'Generate the rolling moon'],
    ],
  },
  {
    id: 'fire', label: 'Fire & anger',
    match: /\b(fire|burn\w*|heat|hot|flames?|lit|angry|anger|rage|mad|furious|smok(e|ing))\b/i,
    meaning: 'Pressure that has to go somewhere.', emotion: 'furious, unstoppable, dangerous',
    motifs: ['light', 'smoke', 'food', 'chrome'],
    ideas: [
      ['literal', 0, 'A match struck in total darkness, lighting only the artist’s eyes.', 'Heat introduced in one sharp moment.', 'Total dark / Strike on the beat / Hold the match near your face safely', 'ECU|eye level|static|2x|60|match flame|dark room|matches', 'cheap,solo,minimal', 'light'],
      ['object', 1, 'A kettle on the stove, whistling louder and louder, in close-up.', 'Anger as something boiling toward a scream.', 'Boil a kettle / Shoot the spout / Cut on the whistle', 'ECU|eye level|static|2x|60|stove glow|kitchen|kettle', 'cheap,minimal', 'food,smoke'],
      ['metaphor', 1, 'The artist irons a white shirt so hard it starts to scorch in the shape of a handprint.', 'Controlled domestic calm with rage underneath.', 'Iron calmly / Press harder each line / Reveal a scorched mark (pre-made)', 'CU|overhead|static|1x|24|laundry room light|laundry|iron;shirt', 'solo,cinematic', 'smoke'],
      ['weird', 2, 'The artist calmly toasts marshmallows on the burning bonnet of his own car.', 'He’s at peace with the damage — even enjoying it.', 'Use a safe flame prop / Sit on a chair beside / Toast slowly', 'MS|eye level|static|1x|24|firelight|empty lot|marshmallows;chair', 'surreal,cinematic', 'cars,food', 'Composite fire safely onto the car'],
      ['weird', 1, 'A birthday cake with candles that keep relighting no matter how hard he blows.', 'Anger he can’t put out.', 'Use trick candles / Blow on the beat / Look annoyed', 'CU|eye level|static|1x|30|candle light|table|cake;trick candles', 'cheap,surreal', 'food,light'],
      ['practical', 0, 'Red LED light, the artist punching a pillow in slow motion, feathers everywhere.', 'Rage made soft and beautiful.', 'Red light only / Punch on the beat / Shoot at 120fps', 'MS|eye level|static|1x|120|red LED|bedroom|pillow', 'cheap,solo', 'light'],
      ['hybrid', 2, 'The artist exhales and the air in front of him ripples like heat off a highway.', 'He is the heat source.', 'Exhale on the lyric / Hold still / Plain background', 'MCU|eye level|static|2x|24|hard side light|anywhere|', 'ai', 'smoke', 'Heat-haze distortion effect'],
    ],
  },
  {
    id: 'time', label: 'Time',
    match: /\b(time|clock|minutes?|hours?|years?|wait\w*|forever|seconds?|tick\w*|patience|late)\b/i,
    meaning: 'Time passing — waiting, wasting or running out.', emotion: 'impatient, reflective, anxious',
    motifs: ['chairs', 'light', 'food'],
    ideas: [
      ['literal', 0, 'A wall clock over the artist’s head, second hand jumping on every beat.', 'Time literally keeping the beat.', 'Frame the clock above you / Sync cuts to the tick', 'MS|eye level|static|1x|24|room light|kitchen|clock', 'cheap,solo', 'light'],
      ['object', 0, 'Ice cream melting completely in one cut while the artist hasn’t moved.', 'Time you can see pass.', 'Shoot a timelapse of melting / Artist still in the same pose / Cut', 'MS|eye level|locked-off|1x|timelapse|daylight|bench|ice cream', 'cheap,solo', 'food,ice'],
      ['metaphor', 1, 'The artist waits in a waiting room; every cut, the other people are older.', 'Waiting on something while life passes.', 'Same seats, re-cast or age with makeup / Artist unchanged', 'WS|eye level|locked-off|0.5x|24|fluorescent|waiting room|chairs', 'crew,cinematic', 'chairs'],
      ['weird', 2, 'The artist wears ten watches up both arms, each showing a different year.', 'Living in every time at once.', 'Stack watches / Check them one by one / Look at camera on the lyric', 'CU|eye level|static|2x|24|warm light|anywhere|watches', 'surreal,luxury', 'chrome'],
      ['weird', 1, 'A barber gives the artist a haircut that grows back between beats.', 'Time undoing progress.', 'Two haircuts or a wig / Cut between / Barber keeps working', 'MS|eye level|static|1x|24|barber light|barbershop|', 'surreal,street', 'chrome'],
      ['practical', 0, 'Timelapse of shadows crossing the artist sitting still on a step, from noon to dusk.', 'A whole day compressed into a line.', 'Tripod / Sit still for short bursts / Timelapse mode', 'WS|eye level|locked-off|0.5x|timelapse|sunlight|front step|tripod', 'cheap,solo,minimal', 'light'],
      ['hybrid', 2, 'The artist walks while the city around him ages decades in a single shot.', 'He moves forward; the world rushes past in years.', 'Steady walk / Locked camera / Busy background', 'WS|eye level|static|0.5x|24|daylight|street|', 'ai,cinematic', 'glass', 'AI ageing of the environment'],
    ],
  },
  {
    id: 'home', label: 'Home & family',
    match: /\b(home|mama|mom|mother|mum|father|dad|papa|family|brother|sister|kasi|hood|block|kids?|grandma|gogo)\b/i,
    meaning: 'Where you come from — love, obligation and memory.', emotion: 'loyal, nostalgic, protective',
    motifs: ['food', 'chairs', 'light', 'televisions'],
    ideas: [
      ['literal', 0, 'The family dinner table with one empty chair saved for the artist.', 'Home waiting for you.', 'Family eats / Artist walks in on the lyric / Sits in the empty chair', 'WS|eye level|static|0.5x|24|warm practicals|home kitchen|table', 'crew,emotional', 'food,chairs'],
      ['object', 0, 'A pot on the stove being stirred by different hands every cut — mother, brother, the artist.', 'Home as a recipe passed down.', 'Same pot, same framing / Change hands per beat', 'CU|overhead|static|1x|24|kitchen light|kitchen|pot', 'cheap,emotional', 'food'],
      ['metaphor', 1, 'The artist’s childhood bedroom rebuilt in the middle of a busy street.', 'He carries home into the world.', 'Move a bed, lamp and posters outside / Sit on the bed / Traffic passes', 'WS|eye level|static|0.5x|24|daylight|street corner|bed;lamp;posters', 'surreal,street', 'chairs,light'],
      ['weird', 2, 'The whole family watches TV, but the TV shows the artist watching them.', 'Home and the one who left looking at each other.', 'Film artist separately / Play it on the TV / Family reacts quietly', 'WS|behind sofa|static|0.5x|24|TV glow|living room|TV', 'surreal,emotional', 'televisions', 'Screen replacement if needed'],
      ['weird', 1, 'The artist’s mother irons his stage outfit on the bonnet of his car.', 'Care and ambition in the same image.', 'Set up on the car / Mother irons calmly / Artist waits', 'MS|eye level|static|1x|24|morning light|driveway|iron;outfit', 'street,emotional', 'cars'],
      ['practical', 0, 'Handheld walk through the neighbourhood waving at people who wave back on the beat.', 'The block knows him.', 'Walk your actual street / Neighbours wave on cue', 'MS|eye level|handheld|0.5x|30|daylight|home street|', 'cheap,street,crew', 'light'],
      ['hybrid', 1, 'Old family photos on the wall come alive and mouth the chorus.', 'The generations singing along.', 'Frame the photo wall / Artist stands beside', 'MS|eye level|static|1x|24|warm light|hallway|photos', 'ai,emotional', 'mirrors', 'Animate photos (AI lip-sync)'],
    ],
  },
  {
    id: 'fame', label: 'Fame & spotlight',
    match: /\b(fame|famous|star|stars|spotlight|stage|crowd|fans?|paparazzi|flash\w*|viral|celebrity|blow(ing)? up)\b/i,
    meaning: 'Being seen by everyone and known by no one.', emotion: 'electric, hollow, hungry',
    motifs: ['light', 'televisions', 'glass', 'cctv'],
    ideas: [
      ['literal', 0, 'Phone camera flashes going off in the dark, each lighting the artist for a frame.', 'Fame as flashes — brief, blinding, repeated.', 'Friends fire flashes on beats / Otherwise dark', 'MS|eye level|static|1x|24|flash only|dark room|phones', 'cheap,crew', 'light'],
      ['object', 1, 'A spotlight follows the artist while he does ordinary chores.', 'Fame follows you even to the sink.', 'Torch or LED as spotlight / Wash dishes / Light tracks you', 'MS|eye level|static|0.5x|24|hard spot|kitchen|torch', 'cheap,solo,surreal', 'light,food'],
      ['metaphor', 1, 'The artist signs autographs for a queue of mannequins.', 'Attention from people who aren’t really there.', 'Line up mannequins / Sign and smile / No reaction from them', 'WS|eye level|static|0.5x|24|shop light|shop floor|mannequins;pen', 'surreal,cinematic', 'plastic'],
      ['weird', 2, 'Paparazzi photograph the artist asleep in bed, flashes lighting the room like lightning.', 'No privacy left — even dreams are content.', 'Sleep / Crew shoots flashes / Don’t wake up', 'WS|high angle|static|0.5x|24|flash only|bedroom|cameras', 'surreal,crew', 'light,cctv'],
      ['weird', 1, 'A red carpet rolled out through a supermarket as the artist buys milk.', 'Ordinary life as a premiere.', 'Lay a red cloth down an aisle / Walk with a basket / Cameras flash', 'WS|eye level|backwards tracking|0.5x|24|store light|supermarket|red cloth', 'street,surreal', 'food,light'],
      ['practical', 0, 'Performance lit only by a ring of phone torches held by friends around the artist.', 'The audience literally is the light.', 'Friends circle with torches / Perform in the centre', 'MS|low angle|slow orbit|0.5x|30|phone torches|dark room|phones', 'cheap,crew', 'light'],
      ['hybrid', 2, 'A giant billboard of the artist blinks and looks down at the real him on the street.', 'The image watching the person.', 'Stand under a billboard / Look up on the lyric', 'WS|low angle|static|0.5x|24|night|street|', 'ai,cinematic', 'televisions', 'Replace billboard content with animated artist'],
    ],
  },
  {
    id: 'faith', label: 'Faith & prayer',
    match: /\b(pray\w*|god|blessed|bless\w*|heaven|church|faith|amen|angels?|lord|holy|grace)\b/i,
    meaning: 'Hope bigger than your circumstances.', emotion: 'grateful, humble, uplifted',
    motifs: ['light', 'water', 'glass'],
    ideas: [
      ['literal', 0, 'Hands folded, lit by a sunbeam through a dusty window.', 'Grace as light arriving.', 'Find a sunbeam / Kneel into it / Dust in the air', 'CU|eye level|static|2x|60|sun shaft|room with window|', 'cheap,emotional,minimal', 'light'],
      ['object', 0, 'A glass of water on a windowsill catching a rainbow.', 'Simple blessings, refracted.', 'Glass in direct sun / Find the rainbow / Slow push', 'ECU|eye level|slow push-in|2x|24|direct sun|windowsill|glass', 'cheap,minimal', 'water,glass,light'],
      ['metaphor', 1, 'The artist kneels in a car wash while the machines rinse over him like a baptism.', 'Cleansing in the most everyday place.', 'Use a hand car wash / Kneel / Water falls on the beat', 'MS|eye level|static|0.5x|60|daylight|car wash|', 'street,cinematic', 'water,cars'],
      ['weird', 2, 'The choir in the church are all the artist’s exes, singing his chorus back to him.', 'Forgiveness from the people you hurt.', 'Fill pews with friends in robes / Artist at the front', 'WS|low angle|slow push-in|0.5x|24|church light|church or hall|robes', 'surreal,crew', 'light'],
      ['weird', 1, 'Angel wings made of drying laundry on a washing line behind the artist.', 'Holy made from ordinary chores.', 'Hang white sheets like wings / Stand in front / Wind helps', 'MS|eye level|static|1x|24|backlight|yard|sheets;washing line', 'cheap,surreal', 'light'],
      ['practical', 0, 'Golden-hour silhouette of the artist on a hill, arms open.', 'A classic image of gratitude — keep it clean.', 'Face the sun / Open arms on the chorus', 'WS|low angle|static|0.5x|24|golden hour|hill|', 'cheap,solo', 'light'],
      ['hybrid', 2, 'Streetlights bend down like they’re listening as the artist prays on the pavement.', 'The city bowing with him.', 'Kneel under streetlights / Hold still', 'WS|low angle|static|0.5x|24|streetlights|street|', 'ai,surreal', 'light', 'Animate bending streetlights'],
    ],
  },
  {
    id: 'fake', label: 'Fake & masks',
    match: /\b(fake|mask\w*|pretend\w*|lie|lies|lying|liars?|smile|act\w*|plastic|phony|cap|capping)\b/i,
    meaning: 'Performance in place of truth.', emotion: 'suspicious, cynical, sharp',
    motifs: ['plastic', 'mirrors', 'televisions'],
    ideas: [
      ['literal', 0, 'Friends smiling for a photo; the moment the flash fires, every smile drops.', 'The mask lasting exactly one frame.', 'Pose / Flash on the beat / Everyone goes blank after', 'MS|eye level|static|1x|24|flash|anywhere|', 'cheap,crew', 'light'],
      ['object', 0, 'A bowl of plastic fruit; the artist takes a bite of an apple and it squeaks.', 'Things that look real and aren’t.', 'Get plastic fruit / Bite on the beat / Deadpan', 'CU|eye level|static|1x|24|kitchen light|kitchen|plastic fruit', 'cheap,solo', 'plastic,food'],
      ['metaphor', 1, 'People at a party are wearing printed photos of their own smiling faces as masks.', 'Performed happiness, literally held up.', 'Print face photos on card / Crew holds them / Artist unmasked', 'WS|eye level|slow push-in|0.5x|24|party lights|party|printed masks', 'crew,surreal', 'plastic'],
      ['weird', 2, 'A laugh track plays while the artist tells a friend something serious; the friend laughs on cue.', 'Reactions that are scripted, not felt.', 'Sitcom-style set / Deliver the line / Friend laughs exactly on the track', 'WS|eye level|locked-off|0.5x|24|flat sitcom light|living room|sofa', 'surreal,crew', 'televisions'],
      ['weird', 1, 'The artist peels a face mask off, revealing the same face underneath, then another.', 'No true face left under the performance.', 'Peel-off mask / Repeat per beat / Same expression', 'CU|eye level|static|2x|24|bathroom light|bathroom|peel-off masks', 'cheap,solo,surreal', 'mirrors'],
      ['practical', 0, 'Shoot the artist in a mirror; the reflection smiles while the real face doesn’t.', 'Two faces in one frame.', 'Two takes locked off / Smile in one / Split in edit', 'MS|over the shoulder|locked-off|1x|24|bathroom light|bathroom|mirror', 'cheap,solo', 'mirrors'],
      ['hybrid', 2, 'Everyone in the crowd has the same face — the artist’s — smiling blankly.', 'Surrounded by copies pretending to be people.', 'Artist in a crowd / Others face camera', 'WS|eye level|static|0.5x|24|daylight|crowd|', 'ai,surreal', 'plastic', 'AI face replacement on extras'],
    ],
  },
  {
    id: 'phone', label: 'Calls & screens',
    match: /\b(call\w*|phone|text\w*|ring\w*|dms?|missed calls?|screen|online|message\w*|voicemail|notifications?|call my name)\b/i,
    meaning: 'Connection through a screen — close and far at once.', emotion: 'anxious, hopeful, ignored',
    motifs: ['televisions', 'light', 'glass'],
    ideas: [
      ['literal', 0, 'A phone lighting up face-down on a table, buzzing on every beat.', 'Someone reaching out, unanswered.', 'Phone face down / Call it on beats / Artist ignores it', 'CU|eye level|static|2x|24|screen glow|table|phone', 'cheap,minimal', 'light'],
      ['object', 1, 'An old payphone ringing in an empty street; the artist answers and sings the line into it.', 'Old-fashioned connection for an old feeling.', 'Find a payphone or prop / Pick up on the beat', 'MS|eye level|static|1x|24|streetlight|street|payphone', 'street,cinematic', 'light'],
      ['metaphor', 1, 'The artist’s name is called over a waiting-room speaker, again and again, and he never stands up.', 'Being summoned by someone you won’t go back to.', 'Sit among others / Speaker calls / Don’t move', 'WS|eye level|static|0.5x|24|fluorescent|waiting room|chairs', 'cinematic,crew', 'chairs'],
      ['weird', 2, 'Hundreds of phones on the pavement light up in the shape of a heart as the artist walks past.', 'Every notification is the same person.', 'Lay phones or LED panels in a shape / Walk past / Light on cue', 'WS|overhead|static|0.5x|24|night|pavement|phones', 'surreal,ai', 'light,televisions', 'Optional: generate extra lit screens'],
      ['weird', 1, 'Every light in the street changes colour when someone says the artist’s name.', 'Being named changes the whole environment.', 'Stand in street / Gel lights or grade per beat', 'WS|eye level|static|0.5x|24|coloured streetlights|street|', 'cinematic,surreal', 'light'],
      ['practical', 0, 'Screen-recorded chat bubbles appear beside the artist’s face as he sings.', 'The conversation behind the song.', 'Film a clean close-up / Add chat bubbles in edit', 'CU|eye level|static|1x|30|soft light|anywhere|', 'cheap,solo', 'televisions'],
      ['hybrid', 2, 'The artist steps into his phone screen and walks through a scrolling feed like a hallway.', 'Living inside the conversation.', 'Walk toward camera against plain wall / Composite into feed', 'WS|eye level|static|0.5x|24|even light|studio|', 'ai', 'televisions,glass', 'Composite artist into a 3D scrolling feed'],
    ],
  },
  {
    id: 'escape', label: 'Freedom & escape',
    match: /\b(free\w*|escape\w*|run\w*|ran|runaway|fly|flying|away|leave|leaving|left|get out|break out|exit)\b/i,
    meaning: 'Getting out — the door finally open.', emotion: 'wild, relieved, reckless',
    motifs: ['water', 'light', 'cars', 'glass'],
    ideas: [
      ['literal', 0, 'The artist bursts through a door into bright daylight, camera following.', 'The moment of getting out.', 'Dark corridor / Push the door on the beat / Run into light', 'MS|eye level|follow|0.5x|60|dark to bright|building exit|', 'cheap,solo', 'light'],
      ['object', 0, 'An open birdcage with a phone inside instead of a bird.', 'What kept you trapped.', 'Place phone in cage / Door open / Phone buzzes', 'CU|eye level|static|2x|24|window light|table|birdcage;phone', 'cheap,minimal', 'televisions'],
      ['metaphor', 1, 'The artist walks off a movie set; the camera follows him past the fake walls into the real street.', 'Leaving the script behind.', 'Build a fake wall / Walk through the edge / Keep walking', 'WS|eye level|tracking|0.5x|24|mixed|set edge|flats', 'cinematic,crew', 'glass'],
      ['weird', 2, 'The artist swims out of a car window into open air, as if the street is underwater.', 'Freedom as a different element.', 'Shoot swim motions on a mat / Composite street', 'MS|eye level|static|1x|60|daylight|street|', 'surreal,ai', 'water,cars', 'Underwater composite over street'],
      ['weird', 1, 'Shopping trolley race down an empty car park at sunrise.', 'Childish freedom at the edge of the day.', 'Friend pushes / Artist rides / Camera alongside', 'WS|low angle|tracking|0.5x|60|sunrise|car park|trolley', 'cheap,street,crew', 'cars,light'],
      ['practical', 0, 'Hand out of a moving car window, riding the wind in slow motion.', 'The smallest feeling of flying.', 'Passenger seat / Hand out safely / 120fps', 'CU|eye level|static|1x|120|golden hour|car|', 'cheap,solo', 'cars,light'],
      ['hybrid', 2, 'The artist opens his front door onto an ocean.', 'The exit is bigger than the house.', 'Open door toward camera / Composite sea beyond', 'WS|eye level|static|0.5x|24|daylight|front door|', 'ai,cinematic', 'water', 'Composite ocean through the doorway'],
    ],
  },
  {
    id: 'dream', label: 'Dreams & sleep',
    match: /\b(dream\w*|sleep\w*|wake|woke|awake|nightmare|bed|pillow|dreaming)\b/i,
    meaning: 'The line between wanting and having.', emotion: 'floating, hopeful, unreal',
    motifs: ['water', 'smoke', 'light', 'flowers'],
    ideas: [
      ['literal', 0, 'The artist sleeping, lit by a slowly turning night-light projector.', 'Dreams made visible.', 'Lie still / Star projector on ceiling / Slow push', 'MS|overhead|slow push-in|0.5x|24|projector glow|bedroom|star projector', 'cheap,solo', 'light'],
      ['object', 1, 'A bed made up neatly in the middle of a shallow river.', 'Resting where things keep moving.', 'Place a camp bed in shallow water safely / Lie down / Water flows', 'WS|eye level|static|0.5x|24|daylight|river|camp bed', 'surreal,cinematic', 'water'],
      ['metaphor', 1, 'The artist sleepwalks through a busy market; everyone moves out of his way without looking.', 'Moving through life half-awake.', 'Eyes closed / Arms out / Crew parts naturally', 'WS|eye level|tracking|0.5x|24|daylight|market|', 'street,surreal', 'food'],
      ['weird', 2, 'The artist’s pillow is a cloud that rains lightly on his face while he smiles.', 'Even his dreams are complicated.', 'Lie down / Spray mist from above / Smile', 'CU|overhead|static|1x|60|soft light|bedroom|mist spray', 'surreal,cheap', 'water,smoke'],
      ['weird', 1, 'Every alarm clock in a shop goes off at once as the artist walks in.', 'Reality demanding he wakes up.', 'Shop of clocks or phones / Walk in on the beat', 'WS|eye level|static|0.5x|24|shop light|shop|clocks', 'surreal', 'light'],
      ['practical', 0, 'Slow-motion bubbles drifting past the artist’s face in a dark room.', 'Fragile, floating, about to pop.', 'Bubble machine / Backlight / 120fps', 'CU|eye level|static|2x|120|backlight|dark room|bubble machine', 'cheap,solo', 'water,light'],
      ['hybrid', 2, 'The bedroom floor turns to water; the bed floats out of the window.', 'Drifting into the dream for real.', 'Lie on bed / Plain room / Hold still', 'WS|high angle|static|0.5x|24|moonlight|bedroom|', 'ai,surreal', 'water', 'Generate water floor and floating bed'],
    ],
  },
  {
    id: 'pressure', label: 'Pressure & drowning',
    match: /\b(pressure|drown\w*|under ?water|breathe|breath|can'?t breathe|suffocat\w*|stress\w*|deep end|overwhelm\w*)\b/i,
    meaning: 'Too much to hold at once.', emotion: 'tense, trapped, fighting',
    motifs: ['water', 'glass', 'plastic'],
    ideas: [
      ['literal', 0, 'The artist’s face just under the surface of a bath, eyes open.', 'Pressure as water closing over.', 'Safe shallow bath / Dip on the lyric / Surface on the next', 'CU|overhead|static|1x|60|soft top light|bathroom|bath', 'emotional,solo', 'water'],
      ['object', 0, 'A plastic bottle crushing slowly in a vice.', 'Pressure applied to something that can’t fight back.', 'Vice or hands / Crush on the beat / Slow motion', 'ECU|eye level|static|2x|120|hard light|workshop|bottle', 'cheap,minimal', 'plastic'],
      ['metaphor', 1, 'The artist sits calmly at a desk in an office slowly filling with water.', 'Everyday life while the pressure rises.', 'Sit at desk / Water level added in edit or tank', 'WS|eye level|locked-off|0.5x|24|office light|office|desk', 'cinematic', 'water', 'Rising water via AI or VFX'],
      ['weird', 2, 'The artist tries to sing into a mic sealed inside a jar of water.', 'Trying to speak through the pressure.', 'Mic in a jar / Lean close / Bubbles instead of sound', 'CU|eye level|static|2x|60|backlight|studio|jar;mic prop', 'surreal,solo', 'water,glass'],
      ['weird', 1, 'Everyone in a lift keeps getting in until the artist is pressed flat against the glass.', 'Life crowding in.', 'Glass lift or door / Crew squeezes in / Face on glass', 'MS|through glass|static|1x|24|lift light|lift|', 'crew,surreal', 'elevators,glass'],
      ['practical', 0, 'Clingfilm stretched in front of the lens; the artist pushes a hand through it on the line.', 'Breaking the barrier.', 'Stretch film on a frame / Push through on the beat', 'MS|eye level|static|1x|60|backlight|anywhere|clingfilm', 'cheap,solo', 'plastic'],
      ['hybrid', 2, 'The street outside fills with water to the rooftops while the artist keeps walking on the pavement below.', 'Pressure everywhere, and he carries on.', 'Walk the street / Locked or tracking', 'WS|eye level|tracking|0.5x|24|daylight|street|', 'ai,cinematic', 'water', 'AI underwater street'],
    ],
  },
  {
    id: 'rivals', label: 'Rivals & competition',
    match: /\b(fight\w*|war|battle\w*|enem\w*|opps?|beef|rival\w*|haters?|compet\w*|versus|vs|game|games|play(ing)?)\b/i,
    meaning: 'Competition — the game and who’s winning it.', emotion: 'focused, cocky, alert',
    motifs: ['chairs', 'light', 'chrome'],
    ideas: [
      ['literal', 0, 'Two players face off over a chessboard; the artist makes the winning move on the beat.', 'Strategy over noise.', 'Chessboard / Move on the beat / Opponent reacts', 'CU|eye level|static|1x|24|single lamp|table|chess set', 'cheap,minimal', 'chairs'],
      ['object', 0, 'A trophy cabinet where every trophy has the artist’s face.', 'Winning so much it’s repetitive.', 'Tape photos on trophies / Slow push', 'MS|eye level|slow push-in|1x|24|cabinet light|shelf|trophies', 'cheap,luxury', 'chrome'],
      ['metaphor', 1, 'A boxing match where the artist never throws a punch — he just keeps dancing while the opponent tires.', 'Winning without fighting.', 'Ring or yard / Dance lightly / Opponent swings and misses', 'WS|eye level|orbit|0.5x|60|hard top light|ring|gloves', 'crew,cinematic', 'light'],
      ['weird', 2, 'Musical chairs with the whole crew, but the artist’s chair never disappears.', 'Everyone else gets eliminated; he stays seated.', 'Circle of chairs / Remove one per beat / Artist sits calm', 'WS|high angle|static|0.5x|24|hall light|hall|chairs', 'crew,surreal', 'chairs'],
      ['weird', 1, 'A tug-of-war where the artist pulls alone against twenty people and wins.', 'Confidence against numbers.', 'Rope / Crew leans back / Artist pulls on the downbeat', 'WS|low angle|static|0.5x|60|daylight|field|rope', 'crew,street', 'light'],
      ['practical', 0, 'Split screen: the artist on both sides of a table in an arm wrestle with himself.', 'The real rival is you.', 'Two takes locked off / Switch sides', 'MS|eye level|locked-off|1x|24|lamp|table|', 'cheap,solo', 'chairs', 'Split-screen two takes'],
      ['hybrid', 2, 'Life-size chess on a basketball court, crew as pieces, artist as king moving one square at a time.', 'The game as the neighbourhood.', 'Mark squares on a court / Crew stands in place / Move on beats', 'EWS|overhead|static|0.5x|24|daylight|court|chalk', 'ai,crew', 'chairs', 'Optional AI crowd extension'],
    ],
  },
  {
    id: 'party', label: 'Party & dance',
    match: /\b(party|parties|dance\w*|club|turn up|vibe\w*|move\w*|dancefloor|groove|bounce|shake)\b/i,
    meaning: 'Joy in the body — letting go.', emotion: 'euphoric, loose, loud',
    motifs: ['light', 'chrome', 'food', 'plastic'],
    ideas: [
      ['literal', 0, 'Dance floor lit by one strobe, the artist in the middle frozen between flashes.', 'Energy chopped into moments.', 'Strobe on beats / Freeze poses', 'WS|eye level|static|0.5x|24|strobe|dark room|strobe', 'cheap,crew', 'light'],
      ['object', 0, 'A glass of water on a speaker rippling in perfect rings to the kick drum.', 'The beat made visible.', 'Glass on speaker / Macro / Loud kick', 'ECU|overhead|static|2x|60|top light|speaker|glass', 'cheap,minimal', 'water,glass'],
      ['metaphor', 1, 'Office workers dance on their desks while the manager keeps typing.', 'Joy breaking out of routine.', 'Office set / Crew dances on beats / Manager ignores', 'WS|high angle|static|0.5x|24|office light|office|desks', 'crew,surreal', 'chairs'],
      ['weird', 2, 'A slow dance in a supermarket freezer aisle, everyone in winter coats.', 'Warm feeling, cold setting.', 'Coats / Freezer aisle / Slow dance', 'WS|eye level|slow dolly|0.5x|24|freezer light|supermarket|coats', 'surreal,cinematic', 'ice,food'],
      ['weird', 1, 'The artist dances with a mop in an empty club at closing time as the lights come up.', 'The party continues after everyone leaves.', 'Lights up / Mop as partner / Twirl on beats', 'WS|eye level|static|0.5x|24|house lights|club|mop', 'cheap,solo', 'light'],
      ['practical', 0, 'Phone on the floor facing up; the crew dances over it.', 'The party from the floor’s point of view.', 'Phone face-up / Dance above / Wide lens', 'WS|ground up|static|0.5x|60|party lights|anywhere|', 'cheap,crew', 'light'],
      ['hybrid', 2, 'Every car on the street starts bouncing on its suspension in time with the chorus.', 'The whole city dancing.', 'Stand on a parked-car street / Dance', 'WS|eye level|static|0.5x|24|daylight|street|', 'ai,surreal', 'cars', 'Animate bouncing cars'],
    ],
  },
  {
    id: 'ghost', label: 'Ghosts & memory',
    match: /\b(ghosts?|haunt\w*|memor\w*|remember\w*|past|used to|old me|back then|nostalgi\w*|forgot|forget)\b/i,
    meaning: 'Something that’s gone but still here.', emotion: 'wistful, haunted, tender',
    motifs: ['mirrors', 'glass', 'televisions', 'light'],
    ideas: [
      ['literal', 0, 'Double exposure: the artist now and his younger self in the same room.', 'Past and present sharing the space.', 'Two takes locked off / Blend in edit', 'WS|eye level|locked-off|0.5x|24|window light|childhood room|', 'cheap,emotional', 'light', 'Blend two takes'],
      ['object', 0, 'A dusty old TV playing a home video, the artist’s reflection over it.', 'Memory and reflection overlapping.', 'Play old footage on a TV / Stand in reflection', 'MCU|eye level|static|1x|24|TV glow|living room|old TV', 'cheap,emotional', 'televisions,glass'],
      ['metaphor', 1, 'The artist sits on a bench where a coat keeps its shape as if someone is still wearing it.', 'The absence that still takes up space.', 'Stiffen a coat with wire / Sit beside / Talk to it', 'MS|eye level|static|1x|24|overcast|bench|coat', 'emotional,surreal', 'chairs'],
      ['weird', 2, 'The artist’s reflection in a shop window walks a second behind him, then stops and waves goodbye.', 'The old self left behind in the glass.', 'Two takes / Walk past windows / Reflection timed in edit', 'MS|profile|tracking|1x|24|daylight|shopfronts|', 'surreal,solo', 'mirrors,glass', 'Reflection replacement'],
      ['weird', 1, 'White sheets on a washing line blow into the shape of a person who isn’t there.', 'A ghost made of laundry and wind.', 'Wind or fan / Sheets / Artist watches', 'WS|eye level|static|0.5x|60|backlight|yard|sheets', 'cheap,surreal', 'light'],
      ['practical', 0, 'Projector throws old photos onto the artist’s face in a dark room.', 'Memories literally on him.', 'Phone projector or TV / Face close / Change photo per beat', 'CU|eye level|static|2x|24|projector|dark room|projector', 'cheap,solo', 'light'],
      ['hybrid', 1, 'The artist walks through his old neighbourhood; people from the past fade in and out around him.', 'Memory as a crowd.', 'Walk the street / Steady move', 'WS|eye level|tracking|0.5x|24|daylight|old street|', 'ai,emotional', 'glass', 'Fade in translucent figures'],
    ],
  },
  {
    id: 'crown', label: 'Power & crown',
    match: /\b(kings?|queens?|crowns?|throne|boss|ruler|royal\w*|power\w*|reign|empire|goat)\b/i,
    meaning: 'Authority — owning the room.', emotion: 'regal, cocky, calm',
    motifs: ['chairs', 'chrome', 'food'],
    ideas: [
      ['literal', 0, 'The artist on a high-backed chair at the end of a long table, lit from above.', 'Power as the head of the table.', 'Long table / Sit centre / Hold still', 'WS|eye level|slow push-in|0.5x|24|top light|hall|table;chair', 'cinematic,luxury', 'chairs'],
      ['object', 1, 'A crown made of bottle caps sitting on a plastic garden chair.', 'Street royalty — power built from everyday things.', 'Make the crown / Place on chair / Artist sits down wearing it', 'MS|low angle|static|1x|24|daylight|yard|bottle caps;plastic chair', 'cheap,street', 'plastic,chairs'],
      ['metaphor', 1, 'The artist sits on a barber chair raised on a platform while the barbershop kneels around it.', 'The community chair as a throne.', 'Raise a chair / Crew around / Low angle', 'WS|low angle|static|0.5x|24|barber light|barbershop|', 'street,crew', 'chairs,chrome'],
      ['weird', 2, 'The royal banquet is all kasi food — kotas and chips served on silver platters with white gloves.', 'Luxury language for home food.', 'Silver platters / Waiters in gloves / Artist eats a kota', 'WS|eye level|static|0.5x|24|candle light|hall|platters;food', 'surreal,street,luxury', 'food,chrome'],
      ['weird', 1, 'The artist sits on a throne made of stacked speakers.', 'Ruling through sound.', 'Stack speakers safely / Sit / Speakers play', 'WS|low angle|static|0.5x|24|hard key|studio|speakers', 'street,cinematic', 'chrome'],
      ['practical', 0, 'Low-angle slow push on the artist in an ordinary kitchen chair, lit like a king.', 'Power from the angle and the light, not the set.', 'Low camera / Hard key / Stare', 'MCU|low angle|slow push-in|1x|24|hard side key|kitchen|chair', 'cheap,solo,minimal', 'chairs,light'],
      ['hybrid', 2, 'A crown of light floats above the artist’s head and dims when he looks away.', 'Authority that depends on attention.', 'Clean headroom / Look up and away', 'MCU|eye level|static|1x|24|dark background|anywhere|', 'ai', 'light', 'Generate the light crown'],
    ],
  },
  {
    id: 'grind', label: 'Grind & hunger',
    match: /\b(hungry|hunger|grind\w*|hustl\w*|work\w*|starv\w*|eat|eating|feed|overtime|9 to 5|no sleep)\b/i,
    meaning: 'Effort nobody sees.', emotion: 'determined, tired, proud',
    motifs: ['food', 'chairs', 'light'],
    ideas: [
      ['literal', 0, 'The artist working through the night at a kitchen table covered in notebooks.', 'The unglamorous hours.', 'Night / Lamp / Write fast', 'MS|eye level|static|1x|24|desk lamp|kitchen|notebooks', 'cheap,solo', 'light,food'],
      ['object', 0, 'An empty plate with a fork scraped clean, over and over.', 'Hunger that doesn’t end.', 'Scrape on each beat / Close-up', 'ECU|overhead|static|1x|24|top light|table|plate;fork', 'cheap,minimal', 'food'],
      ['metaphor', 1, 'The artist runs on a treadmill in the middle of a car dealership.', 'Working hard toward things on display.', 'Treadmill among cars / Run / Stare ahead', 'WS|eye level|static|0.5x|24|showroom light|dealership|treadmill', 'surreal,cinematic', 'cars,chrome'],
      ['weird', 2, 'The artist eats his own gold plaque like a sandwich.', 'Hungry enough to consume his own success.', 'Cake or chocolate plaque / Bite on the beat', 'CU|eye level|static|1x|24|warm light|table|edible plaque', 'surreal,luxury', 'food,chrome'],
      ['weird', 1, 'A clock-in machine at the door of his bedroom; he punches in every morning.', 'Life turned into a shift.', 'Prop clock / Punch in on the beat', 'MS|eye level|static|1x|24|morning light|bedroom door|clock prop', 'cheap,surreal', 'light'],
      ['practical', 0, 'Montage of hands at work: sewing, typing, lifting — cut on every beat.', 'The grind is many hands, one rhythm.', 'Film five tasks / Cut per beat', 'CU|various|static|1x|30|natural|various|', 'cheap,crew', 'food'],
      ['hybrid', 2, 'The artist runs on a road that rolls up behind him like a carpet.', 'No going back — only forward.', 'Run toward camera on a road', 'WS|low angle|tracking|0.5x|60|daylight|road|', 'ai', 'cars', 'Generate the rolling road'],
    ],
  },
  {
    id: 'mirror', label: 'Self & reflection',
    match: /\b(mirror\w*|myself|reflect\w*|me vs me|who i am|identity|same|window|glass|twin|double)\b/i,
    meaning: 'Meeting yourself — the self you show and the one you are.', emotion: 'curious, uneasy, honest',
    motifs: ['mirrors', 'glass', 'water'],
    ideas: [
      ['literal', 0, 'The artist sings to his reflection in a shop window at dusk.', 'Talking to yourself in public.', 'Stand close to glass / Sing to the reflection', 'MCU|profile|static|2x|24|dusk|shopfront|', 'cheap,solo', 'mirrors,glass'],
      ['object', 0, 'A cracked phone screen reflecting the artist’s face in pieces.', 'A broken self-image.', 'Face over a cracked phone / Macro / Shift focus', 'ECU|overhead|static|2x|24|soft light|table|cracked phone', 'cheap,minimal', 'glass,televisions'],
      ['metaphor', 1, 'Two versions of the artist sit back to back, one in daylight, one in night light.', 'Two selves sharing one spine.', 'Two takes / Change lighting / Split in edit', 'MS|eye level|locked-off|1x|24|split lighting|room|', 'solo,cinematic', 'light', 'Split-screen composite'],
      ['weird', 2, 'The reflection in a puddle climbs out and walks beside him.', 'The self you hide stepping into the world.', 'Walk past a puddle / Second take as reflection', 'MS|low angle|tracking|1x|24|streetlights|wet street|', 'surreal,ai', 'water,mirrors', 'Composite reflection stepping out'],
      ['weird', 1, 'A room of mirrors where every reflection is a second late.', 'Your past self catching up.', 'Mirror room or two mirrors / Delay in edit', 'MS|eye level|static|1x|24|even light|room|mirrors', 'surreal', 'mirrors', 'Time offset in edit'],
      ['practical', 0, 'Handheld walk past glass buildings; frame only the reflection.', 'The city shows you yourself.', 'Film the reflection not the person', 'MS|profile|tracking|1x|24|daylight|glass buildings|', 'cheap,street,solo', 'glass'],
      ['hybrid', 2, 'The artist steps out of a mirror into the real room.', 'Becoming who you really are.', 'Mirror frame / Step through (door frame) / Match light', 'MS|eye level|static|1x|24|matched light|bedroom|mirror frame', 'ai,cinematic', 'mirrors,glass', 'Composite step-through'],
    ],
  },
  {
    id: 'silence', label: 'Silence',
    match: /\b(quiet|silence|silent|say nothing|shh+|mute\w*|speechless|no words|hush|whisper\w*)\b/i,
    meaning: 'What isn’t said.', emotion: 'tense, intimate, restrained',
    motifs: ['glass', 'light', 'water'],
    ideas: [
      ['literal', 0, 'The artist puts a finger to his lips and the music drops out for a beat.', 'Silence performed.', 'Finger to lips on the lyric / Cut audio for one beat in edit', 'CU|eye level|static|2x|24|soft key|anywhere|', 'cheap,solo,minimal', 'light'],
      ['object', 0, 'A telephone with its cord cut, still sitting in its cradle.', 'A conversation that can’t happen.', 'Cut a cord / Macro', 'ECU|eye level|static|2x|24|lamp|table|old phone', 'cheap,minimal', 'plastic'],
      ['metaphor', 1, 'Two people talk through a soundproof glass window; neither can hear the other.', 'Communication blocked.', 'Glass / Mouth words / No sound', 'MS|profile|static|1x|24|office light|glass wall|', 'cinematic,crew', 'glass'],
      ['weird', 2, 'The artist opens his mouth to sing and moths fly out silently.', 'Words kept in so long they became something else.', 'Open mouth on the lyric / Composite moths', 'CU|eye level|static|2x|60|dark background|anywhere|', 'surreal,ai', 'light', 'Generate moths'],
      ['weird', 1, 'An orchestra plays with no instruments while the artist conducts.', 'Music without sound.', 'Crew mimes / Artist conducts', 'WS|eye level|static|0.5x|24|stage light|hall|', 'crew,surreal', 'chairs'],
      ['practical', 0, 'Underwater-style muffled shot: the artist’s face seen through a glass of water.', 'Sound gone underwater.', 'Glass of water in front of lens / Muffle audio', 'CU|through glass|static|1x|30|backlight|anywhere|glass', 'cheap,solo', 'water,glass'],
      ['hybrid', 2, 'The whole city freezes mid-motion; only the artist keeps moving.', 'The loudest silence.', 'Crew holds still / Artist walks', 'WS|eye level|tracking|0.5x|24|daylight|street|', 'ai,crew', 'glass', 'Freeze-frame composite'],
    ],
  },
  {
    id: 'road', label: 'The journey',
    match: /\b(road|journey|miles|walk\w*|long way|path|travel\w*|going|come far|mileage|step)\b/i,
    meaning: 'How far you’ve come and how far is left.', emotion: 'determined, reflective, tired',
    motifs: ['cars', 'light', 'water'],
    ideas: [
      ['literal', 0, 'The artist walks the white line down the middle of an empty road at dawn.', 'Staying on course.', 'Walk the line / Camera ahead', 'WS|low angle|backwards tracking|0.5x|24|dawn|empty road|', 'cheap,solo', 'cars,light'],
      ['object', 0, 'Worn-out sneakers lined up, one pair for every year.', 'Distance measured in shoes.', 'Line up old shoes / Slow pan', 'CU|ground level|slow pan|1x|24|window light|floor|shoes', 'cheap,minimal', 'plastic'],
      ['metaphor', 1, 'The artist walks on a treadmill in the back of a moving truck — moving and still at once.', 'Going somewhere, but not by his own steps.', 'Truck bed / Treadmill / Road behind', 'WS|eye level|static|0.5x|24|daylight|truck|treadmill', 'surreal,crew', 'cars'],
      ['weird', 2, 'Every street sign the artist passes shows the name of someone he left behind.', 'The journey measured in people.', 'Sign props or edit / Walk past', 'MS|eye level|tracking|1x|24|daylight|street|signs', 'surreal,ai', 'light', 'Replace sign text'],
      ['weird', 1, 'The artist walks in place while the crew carries the scenery past him.', 'Progress as something others help build.', 'Crew carries boards past / Artist walks in place', 'WS|eye level|locked-off|0.5x|24|daylight|yard|boards', 'crew,cheap', 'light'],
      ['practical', 0, 'Feet-level tracking shot of the artist’s steps, cut on every beat.', 'Rhythm of walking = rhythm of the song.', 'Phone low / Walk / Cut per beat', 'CU|ground level|tracking|0.5x|60|daylight|street|', 'cheap,solo', 'light'],
      ['hybrid', 2, 'The road ahead builds itself tile by tile just before each step lands.', 'Faith in the next step.', 'Walk toward camera', 'WS|low angle|tracking|0.5x|24|daylight|open ground|', 'ai', 'light', 'Generate the road building itself'],
    ],
  },
];

// Fallback when a line matches nothing: turn delivery itself into the visual.
export const GENERIC = {
  id: 'statement', label: 'Statement',
  meaning: 'A direct statement — the delivery is the image.', emotion: 'confident', motifs: ['glass', 'light', 'chairs'],
  ideas: [
    ['literal', 0, 'Deliver the line straight to camera in a tight close-up, one hard light.', 'Nothing between the line and the viewer.', 'Tight frame / Hard light / No blinking', 'CU|eye level|static|2x|24|hard key|anywhere|', 'cheap,solo,minimal', 'light'],
    ['object', 0, 'Write the key word of the line on a steamed-up window, then walk away.', 'The lyric left behind as a trace.', 'Steam a window / Write the word / Leave', 'CU|through glass|static|2x|24|backlight|window|', 'cheap,solo', 'glass'],
    ['metaphor', 1, 'The artist tells the line to a stranger on a bus who nods like it’s normal conversation.', 'Making a lyric feel like everyday truth.', 'Sit beside an actor / Deliver naturally', 'MS|eye level|static|1x|24|daylight|bus|', 'street,crew', 'cars'],
    ['weird', 1, 'The artist sings the line into a glass of water; the surface ripples with each word.', 'The words given physical force.', 'Glass close to mouth / Sing / Macro on ripples', 'ECU|eye level|static|2x|60|backlight|table|glass', 'cheap,surreal', 'water,glass'],
    ['weird', 2, 'Everyone in a quiet library mouths the line at the same time as the artist.', 'The line so true everyone knows it.', 'Crew at desks / All mouth the line', 'WS|eye level|slow push-in|0.5x|24|library light|library|books', 'crew,surreal', 'chairs'],
    ['practical', 0, 'Performance shot moving from wide to close on the line, ending on the eyes.', 'Build intimacy with one move.', 'Start wide / Walk in / End close', 'WS|eye level|push-in|0.5x|24|soft key|anywhere|', 'cheap,solo', 'light'],
    ['hybrid', 1, 'The lyric appears as physical letters on the ground that the artist steps over.', 'Words as landscape.', 'Walk across open ground', 'WS|high angle|static|0.5x|24|daylight|open ground|', 'ai', 'light', 'Generate 3D lyric letters'],
  ],
};

// Sound-driven moments: the music itself suggests the image.
export const SONIC = {
  bass: {
    label: 'Bass hit', meaning: 'Impact — the floor moves.', emotion: 'physical, sudden', motifs: ['glass', 'light', 'chairs'],
    ideas: [
      ['literal', 0, 'Every light in the room shuts off on the hit.', 'The sound kills the power.', 'Lights on / Switch off exactly on the hit', 'WS|eye level|static|0.5x|24|room lights|room|', 'cheap,solo', 'light'],
      ['object', 0, 'A glass of water on the table jolts and splashes on the hit.', 'The bass made physical.', 'Tap the table on the hit / Slow motion', 'ECU|eye level|static|2x|120|backlight|table|glass', 'cheap,minimal', 'water,glass'],
      ['metaphor', 1, 'Camera perspective changes violently: cut from eye level to extreme low angle.', 'The world tilts with the drop.', 'Film two angles / Cut on the hit', 'MS|low angle|static|0.5x|24|same light|same spot|', 'cheap,cinematic', 'light'],
      ['weird', 2, 'The room suddenly expands: walls fly back and the artist is alone in a huge empty hall.', 'The bass makes space.', 'Shoot in small room and big hall / Match pose', 'WS|eye level|static|0.5x|24|matched|two rooms|', 'surreal,ai', 'chairs', 'Morph between rooms'],
      ['practical', 0, 'Drop a heavy object into frame exactly on the hit.', 'Weight and timing.', 'Friend drops a bag / Artist doesn’t flinch', 'MS|eye level|static|1x|60|any|anywhere|bag', 'cheap,crew', 'plastic'],
      ['hybrid', 1, 'A shockwave ripples outward from the artist’s feet on the hit.', 'He is the source of the drop.', 'Stamp on the hit / Plain floor', 'WS|low angle|static|0.5x|24|hard top light|floor|', 'ai', 'glass', 'Shockwave distortion'],
    ],
  },
  pause: {
    label: 'Beat pause', meaning: 'The music holds its breath.', emotion: 'suspended', motifs: ['light', 'glass'],
    ideas: [
      ['literal', 0, 'Freeze all movement; the artist stares straight into the lens.', 'Silence answered with stillness.', 'Stop dead on the pause / Eye contact', 'CU|eye level|static|2x|24|hard key|anywhere|', 'cheap,solo,minimal', 'light'],
      ['object', 0, 'A single object falls slowly through the empty frame.', 'Time slowing in the gap.', 'Drop a flower or feather / 240fps', 'WS|eye level|static|1x|240|backlight|empty room|feather', 'cheap,minimal', 'flowers'],
      ['metaphor', 1, 'Visual emptiness: an empty room where the artist was a second ago.', 'Absence fills the silence.', 'Same frame / Step out on the pause', 'WS|eye level|locked-off|0.5x|24|same light|room|', 'cheap,cinematic', 'chairs'],
      ['weird', 2, 'Everyone around the artist freezes mid-step; he walks out of the frozen crowd.', 'Only he keeps moving when the music stops.', 'Crew freezes on cue / Walk through', 'WS|eye level|static|0.5x|24|daylight|street|', 'crew,surreal', 'glass'],
      ['practical', 0, 'Cut to black with only the artist’s breath heard.', 'Let the gap breathe.', 'Record a breath / Black frame in edit', 'CU|eye level|static|2x|24|none|anywhere|', 'cheap,minimal', 'light'],
      ['hybrid', 1, 'Rain stops mid-air during the pause.', 'The world holding still with the song.', 'Shoot in rain or sprinkler / Freeze in edit', 'WS|eye level|static|0.5x|60|backlight|outside|', 'ai,cinematic', 'water', 'Freeze rain drops'],
    ],
  },
  switch: {
    label: 'Beat switch', meaning: 'The rules change.', emotion: 'surprise, new chapter', motifs: ['light', 'mirrors'],
    ideas: [
      ['literal', 0, 'Change the whole look on the switch: colour to black-and-white, handheld to locked-off.', 'A new sound, a new visual rule.', 'Plan the rule change / Cut exactly on the switch', 'MS|eye level|static|1x|24|new lighting|same place|', 'cheap,cinematic', 'light'],
      ['object', 0, 'A light switch flicked on the beat switch.', 'The literal switch, played straight.', 'Macro on a switch / Flick on the beat', 'ECU|eye level|static|2x|60|room|wall|', 'cheap,minimal', 'light'],
      ['metaphor', 1, 'The artist and a stranger swap outfits between cuts.', 'Identity switching with the beat.', 'Two outfits / Swap between takes', 'MS|eye level|static|1x|24|same|street|', 'crew,street', 'mirrors'],
      ['weird', 2, 'Gravity flips: the next section is shot with the camera upside-down, the artist sitting on the ceiling.', 'Everything after the switch is inverted.', 'Flip the phone / Sit on the floor / Rotate in edit', 'WS|eye level|static|0.5x|24|same|room|', 'surreal,cheap', 'chairs'],
      ['practical', 0, 'Whip-pan transition from one location to the next on the switch.', 'Moves you into the new section.', 'Whip right at the end of one take / Whip in at the start of the next', 'MS|eye level|whip pan|0.5x|60|any|two locations|', 'cheap,solo', 'light'],
      ['hybrid', 1, 'The frame shatters like glass and the new section is behind it.', 'Breaking into the next part of the song.', 'Clean end frame / New start frame', 'MS|eye level|static|1x|24|any|any|', 'ai', 'glass', 'Glass-shatter transition'],
    ],
  },
  chorus: {
    label: 'Chorus', meaning: 'The hook — the image people will remember.', emotion: 'peak', motifs: [],
    ideas: [],
  },
  adlib: {
    label: 'Ad-lib', meaning: 'A side comment — room for a small joke.', emotion: 'playful', motifs: ['food', 'plastic'],
    ideas: [
      ['literal', 0, 'Quick insert of a friend reacting to the ad-lib with a straight face.', 'A tiny reaction beat.', 'Film reaction / Insert on the ad-lib', 'CU|eye level|static|2x|24|any|anywhere|', 'cheap,crew', 'food'],
      ['object', 0, 'A toy on a shelf turns its head on the ad-lib.', 'The world overhears.', 'Turn the toy between takes', 'CU|eye level|static|2x|24|any|shelf|toy', 'cheap,surreal', 'plastic'],
      ['weird', 1, 'A pigeon walks into frame and stares at the camera on the ad-lib.', 'The strangest witness.', 'Seeds on the floor / Wait for the moment', 'CU|ground level|static|2x|24|daylight|pavement|seeds', 'street,cheap', 'food'],
      ['practical', 0, 'Text of the ad-lib pops on screen in a hand-drawn font.', 'Give the ad-lib a voice.', 'Add text in edit', 'CU|eye level|static|1x|24|any|any|', 'cheap,solo', 'plastic'],
    ],
  },
};
